Amazon/Controllers/PurchaseController.cs
using Amazon.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Amazon.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRecordRepository repo { get; set; }
        private Cart cart { get; set; }

        public PurchaseController(IPurchaseRecordRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new PurchaseRecord());
        }

        [HttpPost]
        public IActionResult Checkout(PurchaseRecord purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchaseRecord(purchase);
                cart.ClearCart();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Amazon/Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.Infrastructure;
using Amazon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amazon.Pages
{
    public class PurchaseModel : PageModel
    {

        private IBookstoreRepository repo { get; set; }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        public PurchaseModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";

           

        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
            
            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Amazon/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Amazon.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Amazon/Pages/Purchase.cshtml
@page
@model Amazon.Pages.PurchaseModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach(var i in Model.cart.Items)
            {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@i.Book.Price.ToString("c")</td>
            <td>@((i.Book.Price * i.Quantity).ToString("c"))</td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button> 
                </form>
            </td>
        </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-secondary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-secondary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Amazon/Pages/PurchaseCompleted.cshtml
@page
@model Amazon.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Thanks! We hope you enjoy your book</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Amazon/Pages/_PurchaseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        KEANNAMAZON
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>